# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dramos-p <dramos-p@student.42sp.org.br>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/04 23:03:51 by dramos-p          #+#    #+#              #
#    Updated: 2022/01/11 02:37:29 by dramos-p         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = so_long

CC		=	gcc

CFLAGS	=	-Wall -Werror -Wextra -fsanitize=address

SRC_FILES	=	so_long.c\
				util_win.c

SRC_DIR	=	./src

SRCS 	= $(addprefix $(SRC_DIR)/, $(SRC_FILES))

OBJS	= $(SRCS:.c=.o)

LIBS 	=	mlx_linux/libmlx_Linux.a\
			libft/libft.a\

MINILIBX = -Imlx -lX11 -lXext -lm -lz

all: $(NAME)

%.o: %.c
	$(CC) -Wall -Wextra -Werror -I/usr/include -Imlx_linux -O3 -c $< -o $@

$(NAME): $(OBJS)
	make -C mlx_linux
	gcc $(OBJS) $(LIBS) $(MINILIBX) -o $(NAME)

clean:
	rm -rf $(OBJS) $(NAME)

fclean: clean
	rm -rf $(NAME) 

re:	fclean all